export const IPC_CHANNELS = {
  systemGetReadiness: 'novel-loop:system:get-readiness',
  projectsList: 'novel-loop:projects:list',
  projectsChooseDefaultLibrary:
    'novel-loop:projects:choose-default-library',
  projectsCreate: 'novel-loop:projects:create',
  projectsOpenExisting: 'novel-loop:projects:open-existing',
  projectsOpen: 'novel-loop:projects:open',
  projectsRemove: 'novel-loop:projects:remove',
  foundationStart: 'novel-loop:foundation:start',
  foundationGet: 'novel-loop:foundation:get',
  foundationCancel: 'novel-loop:foundation:cancel',
  foundationRead: 'novel-loop:foundation:read',
  planningStart: 'novel-loop:planning:start',
  planningGet: 'novel-loop:planning:get',
  planningCancel: 'novel-loop:planning:cancel',
  planningRead: 'novel-loop:planning:read',
  chapterInspect: 'novel-loop:chapter:inspect',
  chapterStartPlanning: 'novel-loop:chapter:start-planning',
  chapterStartDrafting: 'novel-loop:chapter:start-drafting',
  chapterAdjustMission: 'novel-loop:chapter:adjust-mission',
  chapterAdjustPlan: 'novel-loop:chapter:adjust-plan',
  chapterGet: 'novel-loop:chapter:get',
  chapterCancel: 'novel-loop:chapter:cancel',
  chapterReadPlan: 'novel-loop:chapter:read-plan',
  chapterReadDraft: 'novel-loop:chapter:read-draft',
  chapterReadDraftWorkingCopy: 'novel-loop:chapter:read-draft-working-copy',
  chapterSaveDraftWorkingCopy: 'novel-loop:chapter:save-draft-working-copy',
  chapterDiscardDraftWorkingCopy: 'novel-loop:chapter:discard-draft-working-copy',
  chapterAdoptDraftRevision: 'novel-loop:chapter:adopt-draft-revision',
  chapterSelectDirection: 'novel-loop:chapter:select-direction',
  chapterSaveMissionWorkingCopy:
    'novel-loop:chapter:save-mission-working-copy',
  chapterSavePlanWorkingCopy: 'novel-loop:chapter:save-plan-working-copy',
  chapterAdoptRevision: 'novel-loop:chapter:adopt-revision'
} as const;
